// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0DjlSpIR_aMgBRZy0kYTwhMVdDPYX2Q',
    appId: '1:788720126083:android:0ec874be587babfd9bb3b6',
    messagingSenderId: '788720126083',
    projectId: 'illkam-b2e9e',
    storageBucket: 'illkam-b2e9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRv5mS9E65GhV1sY5N-jgnRDN-DH8cGg',
    appId: '1:788720126083:ios:abedef3fa7a8e7ba9bb3b6',
    messagingSenderId: '788720126083',
    projectId: 'illkam-b2e9e',
    storageBucket: 'illkam-b2e9e.appspot.com',
    iosBundleId: 'com.cleansolution.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDMnssU6Fq8ghOZ1IvgGmUMpWWKPxtWo',
    appId: '1:788720126083:web:eead69b9155c46869bb3b6',
    messagingSenderId: '788720126083',
    projectId: 'illkam-b2e9e',
    authDomain: 'illkam-b2e9e.firebaseapp.com',
    storageBucket: 'illkam-b2e9e.appspot.com',
    measurementId: 'G-T8LWQZ413J',
  );

}
